### ISSUE TITLE
I get NPE when running sample app

### ISSUE THREAD

**Issue by tasegula** [shopgun/shopgun-android-sdk#11]
When trying to see a catalog I get a NPE from an underlaying `VersoFragment`.

In order to make the sample app work, I copied the code in a new project and added 
`implementation 'com.shopgun.android:sdk:4.0.2-beta'` in gradle, alongside the other dependencies.

Steps to reproduce:
> Open App
> Click on "Catalog List"
> Select a Catalog
> Crash

Attached the stacktrace:

```
java.lang.NullPointerException: Attempt to invoke interface method 'int[] com.shopgun.android.verso.VersoSpreadProperty.getPages()' on a null object reference
        at com.shopgun.android.verso.VersoFragment.ensureAdapter(VersoFragment.java:486)
        at com.shopgun.android.verso.VersoFragment.notifyVersoConfigurationChanged(VersoFragment.java:460)
        at com.shopgun.android.sdk.pagedpublicationkit.PagedPublicationFragment.notifyVersoConfigurationChanged(PagedPublicationFragment.java:304)
        at com.shopgun.android.sdk.pagedpublicationkit.PagedPublicationFragment$PagedPublicationOnLoadComplete.onPagesLoaded(PagedPublicationFragment.java:282)
        at com.shopgun.android.sdk.pagedpublicationkit.impl.apiv2.CatalogConfiguration$CatalogListener.ensurePublicationData(CatalogConfiguration.java:218)
        at com.shopgun.android.sdk.pagedpublicationkit.impl.apiv2.CatalogConfiguration$CatalogListener.onRequestIntermediate(CatalogConfiguration.java:199)
        at com.shopgun.android.sdk.pagedpublicationkit.impl.apiv2.CatalogConfiguration$CatalogListener.onRequestIntermediate(CatalogConfiguration.java:184)
        at com.shopgun.android.sdk.requests.LoaderDelivery$LoaderRequestPostBackRunnable.run(LoaderDelivery.java:78)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by tasegula** [comment]
This seems to be fixed in the newest master branch.
