### ISSUE TITLE
BadParcelableException while restoring Catalog

### ISSUE THREAD

**Issue by cosminstefanxp** [shopgun/shopgun-android-sdk#19]
An issue we've encountered in production using the Shopgun SDK is due to a problem in the Parcelable implementation for Catalog:

```
android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.shopgun.android.sdk.g.e
       at android.os.Parcel.readParcelableCreator(Parcel.java:2860)
       at android.os.Parcel.readParcelable(Parcel.java:2782)
       at com.shopgun.android.sdk.model.Catalog.(Catalog.java:715)
       at com.shopgun.android.sdk.model.Catalog$1.createFromParcel(Catalog.java:729)
       at com.shopgun.android.sdk.model.Catalog$1.createFromParcel(Catalog.java:727)
       at android.os.Parcel.readParcelable(Parcel.java:2791)
       at com.shopgun.android.sdk.pagedpublicationkit.impl.apiv2.CatalogConfiguration.(CatalogConfiguration.java:257)
       at com.shopgun.android.sdk.pagedpublicationkit.impl.apiv2.CatalogConfiguration$1.createFromParcel(CatalogConfiguration.java:266)
       at com.shopgun.android.sdk.pagedpublicationkit.impl.apiv2.CatalogConfiguration$1.createFromParcel(CatalogConfiguration.java:263)
       at android.os.Parcel.readParcelable(Parcel.java:2791)
       at com.shopgun.android.sdk.pagedpublicationkit.PagedPublicationFragment$SavedState.(PagedPublicationFragment.java:656)
       at com.shopgun.android.sdk.pagedpublicationkit.PagedPublicationFragment$SavedState$1.createFromParcel(PagedPublicationFragment.java:664)
       at com.shopgun.android.sdk.pagedpublicationkit.PagedPublicationFragment$SavedState$1.createFromParcel(PagedPublicationFragment.java:661)
       at android.os.Parcel.readParcelable(Parcel.java:2791)
       at android.os.Parcel.readValue(Parcel.java:2685)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3052)
       at android.os.BaseBundle.unparcel(BaseBundle.java:257)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:958)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1361)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3223)
       at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:369)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
       at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onCreate(RxAppCompatActivity.java:59)
```

**Comment by AgneseBussone** [comment]
Fix available in 4.0.3-rc3
